version: 1.0
workflows:
  - name: beast
    subclass: WDL
    primaryDescriptorPath: /GEMSTONEtransmission/beast.wdl  # absolute path
    readMePath: /GEMSTONEtransmission/README.md # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
  