version: 1.2
workflows:
  - name: beast
    subclass: WDL
    primaryDescriptorPath: /workflows/beast.wdl  # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
  
  - name: prep_beast
    subclass: WDL
    primaryDescriptorPath: /workflows/workflow_prep_beast.wdl  # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
        
  - name: BactDating
    subclass: WDL
    primaryDescriptorPath: /workflows/bactdate/wf_BactDate.wdl  # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
        
  - name: BactDating_streamline
    subclass: WDL
    primaryDescriptorPath: /workflows/snippy_tree/wf_snippy_tree.wdl  # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
