version: 1.2
workflows:
  - name: beast
    subclass: WDL
    primaryDescriptorPath: /beast.wdl  # absolute path
    readMePath: /README.md # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
  
