version: 1.2
workflows:
  - name: beast
    subclass: WDL
    primaryDescriptorPath: /workflows/beast.wdl  # absolute path
    readMePath: /workflows/beast.wdl # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
  
