version: 1.2
workflows:
  - name: beast
    subclass: WDL
    primaryDescriptorPath: /tree/main/beast.wdl  # absolute path
    readMePath: /tree/main/beast.wdl # absolute path
    authors:
      - name: Samantha Malatesta
        email: smalates@broadinstitute.org
  
