#!/bin/bash

cd /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution

)


oute453bc3a="${tmpDir}/out.$$" erre453bc3a="${tmpDir}/err.$$"
mkfifo "$oute453bc3a" "$erre453bc3a"
trap 'rm "$oute453bc3a" "$erre453bc3a"' EXIT
touch '/cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/stdout' '/cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/stderr'
tee '/cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/stdout' < "$oute453bc3a" &
tee '/cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/stderr' < "$erre453bc3a" >&2 &
(
cd /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution


R --no-save --args /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/inputs/-1731662400/combined.fasta sequence1 sequence2 2025-01-01 2025-01-01<<Rscript
args <- commandArgs(trailingOnly = TRUE)

        idsstart = 2
        idsend = ((length(args)-1)/2)+1
        ids=args[idsstart:idsend]
        datesstart = ((length(args)-1)/2)+2
        datesend= length(args)
        dates=args[datesstart:datesend]
        fasta = args[1]
        
      
        #make tip dates file
        write.table(data.frame(ids, dates), "tip_dates.txt", sep="\t", row.names =F, col.names=F)

        install.packages("beautier")
        library(beautier)

        #create mcmc
        mcmc = create_mcmc(chain_length = 100)

        #create inference model
        inference_model <- create_inference_model(
        tipdates_filename = "tip_dates.txt", mcmc=mcmc)

        #create xml file
        create_beast2_input_file_from_model(
        inference_model=inference_model,
        input_filename = fasta,
        output_filename = "beast_input.xml"
        )
Rscript
)  > "$oute453bc3a" 2> "$erre453bc3a"
echo $? > /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution
sync


)
mv /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/rc.tmp /cromwell-executions/beast/e453bc3a-d369-4e0a-b265-de90bab392dd/call-xmlR/execution/rc
